build:
  - 'docs/**'
  - 'bokehjs/**'
  - 'src/**'
  - 'examples/**'
  - 'MANIFEST.in'
  - 'pyproject.toml'
  - 'setup.py'
  - 'pixi.toml'
  - 'pixi.lock'
  - 'tools/release/**'

codebase:
  - 'src/**'
  - 'examples/**'

typing:
  - 'src/**'

tools:
  - 'tools/**'
  - '!tools/ci/**'
  - 'src/**'

examples:
  - 'src/**'
  - 'examples/**'

unit_test:
  - 'src/**'

jupyter:
  - 'bokehjs/**'
  - 'MANIFEST.in'
  - 'pyproject.toml'
  - 'setup.py'
  - 'pixi.toml'
  - 'pixi.lock'
  - 'tools/release/**'
  - 'src/bokeh/application/handlers/notebook.py'
  - 'src/bokeh/core/_templates/**'
  - 'src/bokeh/core/serialization.py'
  - 'src/bokeh/document/**'
  - 'src/bokeh/embed/**'
  - 'src/bokeh/io/**'
  - 'src/bokeh/jupyter/**'
  - 'src/bokeh/protocol/**'
  - 'src/bokeh/resources.py'
  - 'examples/output/jupyter/**'
  - 'examples/output/marimo/**'
  - 'examples/server/api/notebook_embed.ipynb'
  - 'tests/integration/test_jupyter_extension.py'
  - 'tests/integration/test_marimo.py'
  - 'tests/unit/bokeh/document/**'
  - 'tests/unit/bokeh/embed/**'
  - 'tests/unit/bokeh/io/**'

minimal_deps:
  - 'src/**'

core_deps:
  - 'src/**'

documentation:
  - 'docs/**'
  - 'src/**'
  - 'examples/**'

bokehjs:
  - 'bokehjs/**'

full:
  - '**'
  - '!docs/**'
  - '!tools/**'
  - '!bokehjs/**'
  - '!src/**'
  - '!examples/**'

ci:
  - 'tools/ci/**'
